// Restrição para implementar a qtd de grupos
// this._createConstraints([[1, 'QtdM1'], [-6, 'QtdGrupo']], '>=', 0),
// this._createConstraints([[1, 'QtdM2'], [-6, 'QtdGrupo']], '>=', 0),
// this._createConstraints([[1, 'QtdM3'], [-6, 'QtdGrupo']], '>=', 0),
// this._createConstraints([[1, 'QtdM4'], [-6, 'QtdGrupo']], '>=', 0),
// this._createConstraints([[1, 'QtdM5'], [-6, 'QtdGrupo']], '>=', 0),
// this._createConstraints([[1, 'QtdM6'], [-6, 'QtdGrupo']], '>=', 0),

// this._createConstraints([[1 / 6, 'QtdM1'], [1 / 6, 'QtdM2'], [1 / 6, 'QtdM3'], [1 / 6, 'QtdM4'], [1 / 6, 'QtdM5'], [1 / 6, 'QtdM6'], [-1, 'Media']], '=', 0),


// this._createConstraints([[1, 'QtdM1'], [-1, 'Media']], '<=', 5),
// this._createConstraints([[-1, 'QtdM1'], [1, 'Media']], '<=', 5),
// this._createConstraints([[1, 'QtdM2'], [-1, 'Media']], '<=', 5),
// this._createConstraints([[-1, 'QtdM2'], [1, 'Media']], '<=', 5),
// this._createConstraints([[1, 'QtdM3'], [-1, 'Media']], '<=', 5),
// this._createConstraints([[-1, 'QtdM3'], [1, 'Media']], '<=', 5),
// this._createConstraints([[1, 'QtdM4'], [-1, 'Media']], '<=', 5),
// this._createConstraints([[-1, 'QtdM4'], [1, 'Media']], '<=', 5),
// this._createConstraints([[1, 'QtdM5'], [-1, 'Media']], '<=', 5),
// this._createConstraints([[-1, 'QtdM5'], [1, 'Media']], '<=', 5),
// this._createConstraints([[1, 'QtdM6'], [-1, 'Media']], '<=', 5),
// this._createConstraints([[-1, 'QtdM6'], [1, 'Media']], '<=', 5),


// this._createConstraints([[1, 'QtdM1'], [-1, 'QtdM2']], '<=', 5),
// this._createConstraints([[-1, 'QtdM1'], [1, 'QtdM2']], '<=', 5),
// this._createConstraints([[1, 'QtdM1'], [-1, 'QtdM3']], '<=', 5),
// this._createConstraints([[-1, 'QtdM1'], [1, 'QtdM3']], '<=', 5),
// this._createConstraints([[1, 'QtdM1'], [-1, 'QtdM4']], '<=', 5),
// this._createConstraints([[-1, 'QtdM1'], [1, 'QtdM4']], '<=', 5),
// this._createConstraints([[1, 'QtdM1'], [-1, 'QtdM5']], '<=', 5),
// this._createConstraints([[-1, 'QtdM1'], [1, 'QtdM5']], '<=', 5),
// this._createConstraints([[1, 'QtdM1'], [-1, 'QtdM6']], '<=', 5),
// this._createConstraints([[-1, 'QtdM1'], [1, 'QtdM6']], '<=', 5),

// this._createConstraints([[1, 'QtdM2'], [-1, 'QtdM3']], '<=', 5),
// this._createConstraints([[-1, 'QtdM2'], [1, 'QtdM3']], '<=', 5),
// this._createConstraints([[1, 'QtdM2'], [-1, 'QtdM4']], '<=', 5),
// this._createConstraints([[-1, 'QtdM2'], [1, 'QtdM4']], '<=', 5),
// this._createConstraints([[1, 'QtdM2'], [-1, 'QtdM5']], '<=', 5),
// this._createConstraints([[-1, 'QtdM2'], [1, 'QtdM5']], '<=', 5),
// this._createConstraints([[1, 'QtdM2'], [-1, 'QtdM6']], '<=', 5),
// this._createConstraints([[-1, 'QtdM2'], [1, 'QtdM6']], '<=', 5),

// this._createConstraints([[1, 'QtdM3'], [-1, 'QtdM4']], '<=', 5),
// this._createConstraints([[-1, 'QtdM3'], [1, 'QtdM4']], '<=', 5),
// this._createConstraints([[1, 'QtdM3'], [-1, 'QtdM5']], '<=', 5),
// this._createConstraints([[-1, 'QtdM3'], [1, 'QtdM5']], '<=', 5),
// this._createConstraints([[1, 'QtdM3'], [-1, 'QtdM6']], '<=', 5),
// this._createConstraints([[-1, 'QtdM3'], [1, 'QtdM6']], '<=', 5),

// this._createConstraints([[1, 'QtdM4'], [-1, 'QtdM5']], '<=', 5),
// this._createConstraints([[-1, 'QtdM4'], [1, 'QtdM5']], '<=', 5),
// this._createConstraints([[1, 'QtdM4'], [-1, 'QtdM6']], '<=', 5),
// this._createConstraints([[-1, 'QtdM4'], [1, 'QtdM6']], '<=', 5),

// this._createConstraints([[1, 'QtdM5'], [-1, 'QtdM6']], '<=', 5),
// this._createConstraints([[-1, 'QtdM5'], [1, 'QtdM6']], '<=', 5),